package Hibernate.entity.HibernateTutorial.HibernateTutorial;
// Generated Aug 31, 2017 2:40:18 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Course generated by hbm2java
 */
@Entity
@Table(name = "course")
public class Course implements java.io.Serializable {

	private int idCourse;
	private String endDay;
	private String nameCourse;
	private int numbers;
	private String startDay;

	public Course() {
	}

	public Course(int idCourse, String endDay, String nameCourse, int numbers, String startDay) {
		this.idCourse = idCourse;
		this.endDay = endDay;
		this.nameCourse = nameCourse;
		this.numbers = numbers;
		this.startDay = startDay;
	}

	@Id

	@Column(name = "idCourse", nullable = false)
	public int getIdCourse() {
		return this.idCourse;
	}

	public void setIdCourse(int idCourse) {
		this.idCourse = idCourse;
	}

	@Column(name = "EndDay", nullable = false, length = 10)
	public String getEndDay() {
		return this.endDay;
	}

	public void setEndDay(String endDay) {
		this.endDay = endDay;
	}

	@Column(name = "NameCourse", nullable = false, length = 45)
	public String getNameCourse() {
		return this.nameCourse;
	}

	public void setNameCourse(String nameCourse) {
		this.nameCourse = nameCourse;
	}

	@Column(name = "Numbers", nullable = false)
	public int getNumbers() {
		return this.numbers;
	}

	public void setNumbers(int numbers) {
		this.numbers = numbers;
	}

	@Column(name = "StartDay", nullable = false, length = 10)
	public String getStartDay() {
		return this.startDay;
	}

	public void setStartDay(String startDay) {
		this.startDay = startDay;
	}

}
